<a href="https://colab.research.google.com/github/jshrma14/Google_colab_python/blob/main/Class_4_case_study_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Opening file for reading...

data = open("bank-data.csv")

In [19]:
# Reading data from file 

data.seek(0)
lst = data.readlines()
del lst[0].  # Removed header
print(len(lst)) #Confirmed len

447

In [22]:
# Creating set of uniq jobs

uniq_jobs = set()
for i in lst:
  print(i.split(","))
  uniq_jobs.add(i.split(",")[1])

['20', 'student', 'single', 'yes\n']
['32', 'management', 'single', 'yes\n']
['49', 'technician', 'married', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['33', 'management', 'married', 'yes\n']
['61', 'admin.', 'married', 'yes\n']
['45', 'blue-collar', 'divorced', 'yes\n']
['34', 'technician', 'married', 'yes\n']
['37', 'management', 'married', 'yes\n']
['27', 'admin.', 'divorced', 'yes\n']
['52', 'services', 'married', 'yes\n']
['37', 'management', 'married', 'yes\n']
['27', 'services', 'single', 'yes\n']
['21', 'student', 'single', 'yes\n']
['25', 'student', 'single', 'yes\n']
['25', 'technician', 'single', 'yes\n']
['34', 'self-employed', 'single', 'yes\n']
['52', 'management', 'married', 'yes\n']
['55', 'admin.', 'married', 'yes\n']
['28', 'management', 'single', 'yes\n']
['35', 'technician', 'single', 'yes\n']
['29', 'blue-collar', 'single', 'yes\n']
['42', 'management', 'married', 'yes\n']
['29', 'blue-collar', 'single', 'yes\n']
['24', 'blue-collar', 'single', 'yes\n']
['34', 'admin.', 'married', 'yes\n']
['50', 'blue-collar', 'married', 'yes\n']
['49', 'entrepreneur', 'divorced', 'yes\n']
['45', 'blue-collar', 'divorced', 'yes\n']
['38', 'entrepreneur', 'married', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['49', 'entrepreneur', 'married', 'yes\n']
['25', 'admin.', 'single', 'yes\n']
['35', 'entrepreneur', 'married', 'yes\n']
['38', 'management', 'married', 'yes\n']
['35', 'entrepreneur', 'single', 'yes\n']
['32', 'services', 'married', 'yes\n']
['30', 'management', 'single', 'yes\n']
['55', 'management', 'married', 'yes\n']
['48', 'admin.', 'divorced', 'yes\n']
['60', 'technician', 'single', 'yes\n']
['37', 'management', 'married', 'yes\n']
['28', 'blue-collar', 'single', 'yes\n']
['54', 'admin.', 'married', 'yes\n']
['49', 'management', 'divorced', 'yes\n']
['30', 'management', 'married', 'yes\n']
['35', 'technician', 'married', 'yes\n']
['34', 'self-employed', 'single', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['61', 'admin.', 'married', 'yes\n']
['53', 'admin.', 'married', 'yes\n']
['46', 'admin.', 'married', 'yes\n']
['44', 'technician', 'single', 'yes\n']
['19', 'student', 'single', 'yes\n']
['30', 'blue-collar', 'single', 'yes\n']
['52', 'technician', 'married', 'yes\n']
['36', 'blue-collar', 'married', 'yes\n']
['47', 'admin.', 'single', 'yes\n']
['43', 'management', 'single', 'yes\n']
['41', 'blue-collar', 'married', 'yes\n']
['28', 'technician', 'single', 'yes\n']
['32', 'services', 'single', 'yes\n']
['41', 'self-employed', 'married', 'yes\n']
['35', 'technician', 'married', 'yes\n']
['30', 'management', 'single', 'yes\n']
['58', 'self-employed', 'divorced', 'yes\n']
['27', 'management', 'single', 'yes\n']
['39', 'management', 'married', 'yes\n']
['46', 'self-employed', 'married', 'yes\n']
['28', 'management', 'single', 'yes\n']
['38', 'technician', 'single', 'yes\n']
['28', 'services', 'single', 'yes\n']
['32', 'management', 'divorced', 'yes\n']
['35', 'self-employed', 'divorced', 'yes\n']
['50', 'management', 'married', 'yes\n']
['36', 'technician', 'married', 'yes\n']
['28', 'management', 'single', 'yes\n']
['48', 'management', 'married', 'yes\n']
['29', 'blue-collar', 'single', 'yes\n']
['34', 'management', 'married', 'yes\n']
['43', 'management', 'married', 'yes\n']
['47', 'blue-collar', 'married', 'yes\n']
['39', 'services', 'single', 'yes\n']
['55', 'housemaid', 'divorced', 'yes\n']
['46', 'management', 'divorced', 'yes\n']
['41', 'admin.', 'single', 'yes\n']
['31', 'housemaid', 'single', 'yes\n']
['26', 'admin.', 'single', 'yes\n']
['60', 'technician', 'married', 'yes\n']
['27', 'student', 'single', 'yes\n']
['28', 'services', 'single', 'yes\n']
['34', 'blue-collar', 'divorced', 'yes\n']
['34', 'management', 'married', 'yes\n']
['40', 'blue-collar', 'married', 'yes\n']
['41', 'technician', 'married', 'yes\n']
['33', 'management', 'single', 'yes\n']
['58', 'self-employed', 'married', 'yes\n']
['34', 'blue-collar', 'single', 'yes\n']
['43', 'management', 'divorced', 'yes\n']
['59', 'self-employed', 'married', 'yes\n']
['37', 'admin.', 'married', 'yes\n']
['45', 'technician', 'single', 'yes\n']
['49', 'blue-collar', 'married', 'yes\n']
['42', 'technician', 'married', 'yes\n']
['45', 'admin.', 'married', 'yes\n']
['55', 'blue-collar', 'divorced', 'yes\n']
['34', 'services', 'married', 'yes\n']
['63', 'entrepreneur', 'married', 'yes\n']
['48', 'management', 'married', 'yes\n']
['36', 'blue-collar', 'married', 'yes\n']
['38', 'admin.', 'married', 'yes\n']
['33', 'blue-collar', 'married', 'yes\n']
['59', 'technician', 'married', 'yes\n']
['37', 'technician', 'married', 'yes\n']
['37', 'technician', 'married', 'yes\n']
['60', 'management', 'divorced', 'yes\n']
['44', 'admin.', 'married', 'yes\n']
['32', 'technician', 'single', 'yes\n']
['33', 'management', 'married', 'yes\n']
['28', 'self-employed', 'single', 'yes\n']
['37', 'management', 'married', 'yes\n']
['31', 'technician', 'married', 'yes\n']
['34', 'services', 'married', 'yes\n']
['61', 'management', 'married', 'yes\n']
['36', 'management', 'single', 'yes\n']
['60', 'blue-collar', 'married', 'yes\n']
['27', 'technician', 'single', 'yes\n']
['41', 'management', 'divorced', 'yes\n']
['46', 'admin.', 'divorced', 'yes\n']
['31', 'management', 'married', 'yes\n']
['32', 'management', 'single', 'yes\n']
['42', 'management', 'married', 'yes\n']
['49', 'management', 'married', 'yes\n']
['45', 'admin.', 'married', 'yes\n']
['32', 'management', 'single', 'yes\n']
['27', 'admin.', 'married', 'yes\n']
['47', 'technician', 'married', 'yes\n']
['28', 'management', 'single', 'yes\n']
['46', 'admin.', 'married', 'yes\n']
['38', 'technician', 'married', 'yes\n']
['35', 'blue-collar', 'single', 'yes\n']
['38', 'services', 'single', 'yes\n']
['36', 'management', 'married', 'yes\n']
['56', 'housemaid', 'divorced', 'yes\n']
['32', 'technician', 'single', 'yes\n']
['31', 'management', 'married', 'yes\n']
['45', 'services', 'single', 'yes\n']
['36', 'management', 'married', 'yes\n']
['31', 'blue-collar', 'married', 'yes\n']
['53', 'services', 'divorced', 'yes\n']
['59', 'technician', 'married', 'yes\n']
['29', 'technician', 'single', 'yes\n']
['46', 'technician', 'married', 'yes\n']
['47', 'admin.', 'divorced', 'yes\n']
['42', 'admin.', 'divorced', 'yes\n']
['33', 'technician', 'married', 'yes\n']
['54', 'management', 'divorced', 'yes\n']
['28', 'student', 'single', 'yes\n']
['42', 'management', 'divorced', 'yes\n']
['49', 'management', 'single', 'yes\n']
['46', 'management', 'divorced', 'yes\n']
['39', 'self-employed', 'single', 'yes\n']
['53', 'blue-collar', 'married', 'yes\n']
['52', 'blue-collar', 'divorced', 'yes\n']
['47', 'services', 'single', 'yes\n']
['32', 'technician', 'single', 'yes\n']
['37', 'technician', 'single', 'yes\n']
['43', 'admin.', 'married', 'yes\n']
['31', 'management', 'single', 'yes\n']
['35', 'management', 'single', 'yes\n']
['25', 'student', 'single', 'yes\n']
['32', 'blue-collar', 'single', 'yes\n']
['46', 'admin.', 'married', 'yes\n']
['48', 'management', 'married', 'yes\n']
['34', 'technician', 'married', 'yes\n']
['53', 'admin.', 'single', 'yes\n']
['40', 'admin.', 'single', 'yes\n']
['49', 'housemaid', 'married', 'yes\n']
['49', 'admin.', 'married', 'yes\n']
['29', 'management', 'single', 'yes\n']
['38', 'technician', 'married', 'yes\n']
['35', 'technician', 'married', 'yes\n']
['57', 'blue-collar', 'married', 'yes\n']
['51', 'management', 'single', 'yes\n']
['31', 'management', 'married', 'yes\n']
['39', 'technician', 'divorced', 'yes\n']
['54', 'management', 'married', 'yes\n']
['51', 'self-employed', 'married', 'yes\n']
['34', 'management', 'single', 'yes\n']
['47', 'blue-collar', 'married', 'yes\n']
['34', 'admin.', 'married', 'yes\n']
['26', 'blue-collar', 'single', 'yes\n']
['39', 'technician', 'divorced', 'yes\n']
['42', 'management', 'married', 'yes\n']
['40', 'management', 'single', 'yes\n']
['28', 'student', 'single', 'yes\n']
['46', 'management', 'married', 'yes\n']
['48', 'housemaid', 'married', 'yes\n']
['30', 'services', 'single', 'yes\n']
['29', 'management', 'single', 'yes\n']
['22', 'student', 'single', 'yes\n']
['27', 'technician', 'single', 'yes\n']
['27', 'student', 'single', 'yes\n']
['42', 'services', 'divorced', 'yes\n']
['41', 'admin.', 'divorced', 'yes\n']
['44', 'technician', 'single', 'yes\n']
['37', 'entrepreneur', 'divorced', 'yes\n']
['44', 'management', 'married', 'yes\n']
['40', 'management', 'single', 'yes\n']
['34', 'technician', 'single', 'yes\n']
['59', 'management', 'married', 'yes\n']
['41', 'blue-collar', 'divorced', 'yes\n']
['30', 'management', 'married', 'yes\n']
['59', 'technician', 'married', 'yes\n']
['31', 'admin.', 'single', 'yes\n']
['48', 'technician', 'married', 'yes\n']
['47', 'technician', 'married', 'yes\n']
['33', 'blue-collar', 'single', 'yes\n']
['30', 'management', 'single', 'yes\n']
['38', 'management', 'single', 'yes\n']
['33', 'management', 'married', 'yes\n']
['41', 'admin.', 'married', 'yes\n']
['35', 'housemaid', 'married', 'yes\n']
['47', 'housemaid', 'single', 'yes\n']
['37', 'management', 'married', 'yes\n']
['62', 'management', 'married', 'yes\n']
['33', 'services', 'married', 'yes\n']
['40', 'services', 'married', 'yes\n']
['28', 'blue-collar', 'single', 'yes\n']
['43', 'entrepreneur', 'married', 'yes\n']
['23', 'entrepreneur', 'single', 'yes\n']
['29', 'management', 'married', 'yes\n']
['34', 'management', 'married', 'yes\n']
['24', 'student', 'single', 'yes\n']
['44', 'technician', 'married', 'yes\n']
['33', 'blue-collar', 'married', 'yes\n']
['24', 'services', 'married', 'yes\n']
['37', 'management', 'married', 'yes\n']
['41', 'management', 'married', 'yes\n']
['35', 'admin.', 'single', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['27', 'services', 'single', 'yes\n']
['30', 'management', 'married', 'yes\n']
['37', 'technician', 'single', 'yes\n']
['43', 'services', 'single', 'yes\n']
['35', 'services', 'married', 'yes\n']
['41', 'blue-collar', 'single', 'yes\n']
['44', 'management', 'single', 'yes\n']
['51', 'technician', 'married', 'yes\n']
['35', 'management', 'married', 'yes\n']
['36', 'management', 'married', 'yes\n']
['23', 'technician', 'single', 'yes\n']
['22', 'student', 'single', 'yes\n']
['35', 'admin.', 'divorced', 'yes\n']
['37', 'management', 'married', 'yes\n']
['53', 'housemaid', 'married', 'yes\n']
['44', 'technician', 'divorced', 'yes\n']
['31', 'management', 'married', 'yes\n']
['33', 'management', 'married', 'yes\n']
['34', 'admin.', 'divorced', 'yes\n']
['52', 'technician', 'married', 'yes\n']
['49', 'services', 'married', 'yes\n']
['50', 'management', 'single', 'yes\n']
['36', 'management', 'married', 'yes\n']
['45', 'blue-collar', 'single', 'yes\n']
['36', 'management', 'married', 'yes\n']
['42', 'technician', 'married', 'yes\n']
['27', 'student', 'single', 'yes\n']
['31', 'management', 'married', 'yes\n']
['29', 'management', 'single', 'yes\n']
['45', 'admin.', 'divorced', 'yes\n']
['55', 'management', 'divorced', 'yes\n']
['25', 'management', 'single', 'yes\n']
['41', 'blue-collar', 'single', 'yes\n']
['29', 'technician', 'single', 'yes\n']
['32', 'technician', 'single', 'yes\n']
['53', 'blue-collar', 'married', 'yes\n']
['47', 'technician', 'married', 'yes\n']
['40', 'blue-collar', 'married', 'yes\n']
['61', 'management', 'married', 'yes\n']
['35', 'management', 'divorced', 'yes\n']
['19', 'student', 'single', 'yes\n']
['46', 'technician', 'divorced', 'yes\n']
['38', 'entrepreneur', 'married', 'yes\n']
['37', 'technician', 'single', 'yes\n']
['39', 'management', 'married', 'yes\n']
['49', 'services', 'married', 'yes\n']
['43', 'blue-collar', 'married', 'yes\n']
['44', 'management', 'married', 'yes\n']
['38', 'technician', 'married', 'yes\n']
['32', 'technician', 'single', 'yes\n']
['51', 'housemaid', 'divorced', 'yes\n']
['32', 'management', 'married', 'yes\n']
['35', 'technician', 'single', 'yes\n']
['32', 'management', 'single', 'yes\n']
['34', 'housemaid', 'married', 'yes\n']
['41', 'technician', 'single', 'yes\n']
['49', 'blue-collar', 'married', 'yes\n']
['61', 'technician', 'married', 'yes\n']
['45', 'management', 'married', 'yes\n']
['36', 'management', 'single', 'yes\n']
['22', 'student', 'single', 'yes\n']
['31', 'management', 'single', 'yes\n']
['56', 'admin.', 'married', 'yes\n']
['46', 'admin.', 'married', 'yes\n']
['34', 'technician', 'single', 'yes\n']
['38', 'entrepreneur', 'single', 'yes\n']
['60', 'admin.', 'married', 'yes\n']
['51', 'self-employed', 'married', 'yes\n']
['49', 'technician', 'married', 'yes\n']
['40', 'management', 'married', 'yes\n']
['39', 'blue-collar', 'married', 'yes\n']
['50', 'technician', 'divorced', 'yes\n']
['34', 'admin.', 'married', 'yes\n']
['43', 'management', 'single', 'yes\n']
['33', 'services', 'married', 'yes\n']
['31', 'technician', 'single', 'yes\n']
['30', 'blue-collar', 'single', 'yes\n']
['47', 'services', 'married', 'yes\n']
['48', 'management', 'married', 'yes\n']
['32', 'admin.', 'single', 'yes\n']
['27', 'management', 'married', 'yes\n']
['24', 'technician', 'married', 'yes\n']
['28', 'admin.', 'single', 'yes\n']
['34', 'management', 'single', 'yes\n']
['55', 'management', 'married', 'yes\n']
['41', 'management', 'married', 'yes\n']
['52', 'blue-collar', 'married', 'yes\n']
['54', 'technician', 'married', 'yes\n']
['36', 'management', 'married', 'yes\n']
['36', 'blue-collar', 'married', 'yes\n']
['28', 'self-employed', 'single', 'yes\n']
['60', 'services', 'married', 'yes\n']
['40', 'blue-collar', 'single', 'yes\n']
['33', 'admin.', 'married', 'yes\n']
['25', 'management', 'single', 'yes\n']
['35', 'blue-collar', 'divorced', 'yes\n']
['53', 'management', 'married', 'yes\n']
['33', 'admin.', 'married', 'yes\n']
['53', 'admin.', 'married', 'yes\n']
['27', 'admin.', 'married', 'yes\n']
['46', 'services', 'married', 'yes\n']
['33', 'self-employed', 'single', 'yes\n']
['39', 'self-employed', 'married', 'yes\n']
['55', 'technician', 'married', 'yes\n']
['28', 'student', 'single', 'yes\n']
['47', 'management', 'married', 'yes\n']
['58', 'services', 'divorced', 'yes\n']
['32', 'management', 'divorced', 'yes\n']
['43', 'technician', 'married', 'yes\n']
['33', 'services', 'divorced', 'yes\n']
['49', 'technician', 'married', 'yes\n']
['61', 'self-employed', 'divorced', 'yes\n']
['43', 'blue-collar', 'married', 'yes\n']
['38', 'management', 'married', 'yes\n']
['52', 'management', 'single', 'yes\n']
['29', 'admin.', 'single', 'yes\n']
['29', 'services', 'divorced', 'yes\n']
['26', 'services', 'single', 'yes\n']
['32', 'services', 'married', 'yes\n']
['36', 'entrepreneur', 'married', 'yes\n']
['30', 'blue-collar', 'single', 'yes\n']
['30', 'admin.', 'single', 'yes\n']
['80', 'housemaid', 'married', 'yes\n']
['31', 'management', 'married', 'yes\n']
['32', 'services', 'single', 'yes\n']
['43', 'technician', 'married', 'yes\n']
['34', 'technician', 'divorced', 'yes\n']
['27', 'services', 'married', 'yes\n']
['36', 'blue-collar', 'divorced', 'yes\n']
['42', 'admin.', 'single', 'yes\n']
['36', 'management', 'single', 'yes\n']
['55', 'technician', 'divorced', 'yes\n']
['61', 'management', 'married', 'yes\n']
['35', 'management', 'married', 'yes\n']
['26', 'management', 'single', 'yes\n']
['47', 'management', 'married', 'yes\n']
['33', 'admin.', 'married', 'yes\n']
['53', 'services', 'divorced', 'yes\n']
['46', 'technician', 'divorced', 'yes\n']
['29', 'housemaid', 'single', 'yes\n']
['39', 'admin.', 'married', 'yes\n']
['54', 'technician', 'married', 'yes\n']
['26', 'student', 'single', 'yes\n']
['44', 'technician', 'single', 'yes\n']
['47', 'management', 'single', 'yes\n']
['31', 'services', 'divorced', 'yes\n']
['36', 'blue-collar', 'married', 'yes\n']
['42', 'management', 'married', 'yes\n']
['30', 'technician', 'married', 'yes\n']
['36', 'technician', 'single', 'yes\n']
['47', 'admin.', 'married', 'yes\n']
['25', 'management', 'married', 'yes\n']
['34', 'management', 'married', 'yes\n']
['49', 'management', 'married', 'yes\n']
['44', 'self-employed', 'single', 'yes\n']
['34', 'admin.', 'single', 'yes\n']
['37', 'blue-collar', 'divorced', 'yes\n']
['38', 'housemaid', 'divorced', 'yes\n']
['46', 'blue-collar', 'married', 'yes\n']
['52', 'admin.', 'single', 'yes\n']
['53', 'entrepreneur', 'married', 'yes\n']
['28', 'blue-collar', 'married', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['30', 'management', 'married', 'yes\n']
['25', 'student', 'single', 'yes\n']
['47', 'blue-collar', 'divorced', 'yes\n']
['50', 'self-employed', 'divorced', 'yes\n']
['30', 'technician', 'married', 'yes\n']
['55', 'entrepreneur', 'divorced', 'yes\n']
['32', 'blue-collar', 'married', 'yes\n']
['32', 'services', 'single', 'yes\n']
['48', 'blue-collar', 'married', 'yes\n']
['34', 'management', 'married', 'yes\n']
['27', 'blue-collar', 'single', 'yes\n']
['30', 'technician', 'single', 'yes\n']
['33', 'blue-collar', 'single', 'yes\n']
['62', 'self-employed', 'divorced', 'yes\n']
['39', 'services', 'divorced', 'yes\n']
['38', 'technician', 'single', 'yes\n']
['31', 'blue-collar', 'married', 'yes\n']
['33', 'technician', 'single', 'yes\n']
['36', 'technician', 'single', 'yes\n']
['32', 'management', 'single', 'yes\n']
['34', 'housemaid', 'married', 'yes\n']
['59', 'technician', 'married', 'yes\n']
['25', 'student', 'married', 'yes\n']
['53', 'management', 'married', 'yes\n']
['52', 'management', 'married', 'yes\n']
['34', 'admin.', 'divorced', 'yes\n']
['49', 'admin.', 'married', 'yes\n']
['50', 'blue-collar', 'married', 'yes\n']
['29', 'blue-collar', 'single', 'yes\n']
['41', 'entrepreneur', 'married', 'yes\n']
['45', 'admin.', 'divorced', 'yes\n']
['32', 'blue-collar', 'single', 'yes\n']
['45', 'management', 'single', 'yes\n']
['40', 'management', 'married', 'yes\n']
['49', 'blue-collar', 'single', 'yes\n']
['29', 'management', 'single', 'yes\n']
['38', 'management', 'single', 'yes\n']
['38', 'management', 'married', 'yes\n']
['26', 'technician', 'single', 'yes\n']
['60', 'self-employed', 'married', 'yes\n']
['42', 'blue-collar', 'single', 'yes\n']
['32', 'admin.', 'single', 'yes\n']
['46', 'blue-collar', 'married', 'yes\n']

In [23]:
# Set of unique jobs
print(uniq_jobs)

{'management', 'self-employed', 'services', 'blue-collar', 'entrepreneur', 'technician', 'admin.', 'student', 'housemaid'}

In [27]:
profession = input("Enter profession you want to choose..")
count_eligible = 0
if profession in uniq_jobs:
  for j in lst:
    if profession in j.split(","):
      print("This user is eligible")
      count_eligible +=1

print("Total eligible users:",count_eligible)

Enter profession you want to choose..self-employed
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
This user is eligible
Total eligible users: 20

In [ ]:
# For checking by comaand line input:

import sys

profession = sys.argv[1]

count_eligible = 0
if profession in uniq_jobs:
  for j in lst:
    if profession in j.split(","):
      print("This user is eligible")
      count_eligible +=1

print("Total eligible users:",count_eligible)

In [28]:
data.close()